version: '3.7'
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn start:dev
    env_file:
      - .env
    networks: 
      - manage
    depends_on: 
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_USER: testuser1
      MYSQL_PASSWORD: secret123
    ports:
      - "3308:3306"
    volumes: 
      - data:/var/lib/mysql
    networks: 
      - manage

networks: 
  manage:
volumes:
  data: