version: '3.7'
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn start:dev
    env_file:
      - .env
    networks: 
      - manage
    depends_on: 
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD:${DB_PASSWORD}
    volumes: 
      - data:/var/lib/mysql
    networks: 
      - manage

networks: 
  manage:
volumes:
  data: